### ISSUE TITLE
Scroll to top after Ajax content load

### ISSUE THREAD

**Issue by NetworkWebMasters** [mrosata/wp-auto-ajax#1]
Is there anyway that the page will automatically scroll to the top after the content has loaded (via Ajax)?

**Comment by mrosata** [comment]
I can expose some events so that you could hook your JavaScript into them. Then you could just use `window.scrollTop(0,0)` inside one of them. I can do that tomorrow. I could also make an option which does the scrolling automatically. I will look into this tomorrow and get a resolution for you.

**Comment by NetworkWebMasters** [comment]
Thank You So Much For Reply :)
I added this line `$('html, body').animate({ scrollTop: 0 }, 'slow');` Its working perfect now.

How can i change browser url after ajax request complete? and this plugin supports Google “SEO-friendly AJAX” recommendations?

**Comment by mrosata** [comment]
I can add an option to toggle url history as well.

Besides updating the url history I don't believe that we need to do much to support Ajax SEO anymore, in 2009 Google issued a set of Ajax SEO principles but in 2015 they deprecated most of those recommendations because the Google crawler can now see content dynamically rendered during page load where previously they were limited. 
A big consideration on whether or not to change the url after Ajax content is loaded is that the url pushed into history should be "sharable", so if John sends Jane the url in his browser window then she should see the same content he does after visiting the link. 

I think this plugin would meet that consideration, but I'll add the feature as a checkbox option so if it doesn't work as expected on a site it can be shut off.

**Comment by mrosata** [comment]
Here is the link to that Ajax crawling deprecation if your interested, maybe the "SEO-friendly AJAX" recommendations you mentioned aren't the same ones I was thinking about - [https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html)

**Comment by mrosata** [comment]
@NetworkWebMasters  I just added the history feature if you want to check it out.

**Comment by NetworkWebMasters** [comment]
Awesome, urls are working perfectly, Thank You So Much :)
One thing i saw, when we click anywhere, plugin takes too much time to open page (means takes too much time to complete request),
i added "#site-navigation" id in Ajax Menu Selector but it wont detect navigation menu links,
and can you add progress bar that indicate the loading progress of an Ajax request like Github?

**Comment by mrosata** [comment]
Possibly. At the moment I'm busy so I'll try to remember next week. I just did another small update which added this original issue (the events). Now there are 3 events you can hook your JavaScript into. It's explained in the `README.md` on the front page.

You might want to check that you have the "advanced" checked off in the options so it uses the advanced options. Also if you leave the menu selector blank it probably would be better because it will just look at all links on the page, figure out which ones belong to your site based on the url and then it will add the ajax functionality to them. You can inspect the html after to see if the properties for wp-auto-ajax are added to the anchor tags in the HTML. 

In the future I'm going to remove the "basic/advanced" options and make it all just 1 set of options. It would be less confusing. I will try to work on the other suggestions you mentioned as well. Thanks.
